### ISSUE TITLE
Build.bat output

### ISSUE THREAD

**Issue by snailmann32** [GM82Project/gm82net#5]
Is the build file for this extension supposed to only output a dll?
I've tried cramming the dll into an extension maker to get a GEX but it didn't work as intended. It installs, but gm82snd still doesn't recognize it as being there.

**Comment by skyfloogle** [comment]
Do you have Python installed? The gex generator is a Python script [downloaded during the process](https://github.com/GM82Project/gm82net/blob/a3acf86b10d7de6c3947c39dd10b989ad88e4389/src/CMakeLists.txt#L39C7-L47).
Alternatively, you could [download a gex from GitHub Actions](https://github.com/GM82Project/gm82net/actions/runs/6421445116). Most of the repositories here have GitHub actions set up so you can just download the latest version.

**Comment by snailmann32** [comment]
Hmm, I do have Python. I believe it's fairly up to date since I used it for another project a few months ago. 
Oh! I did not know I was supposed to throw the .GEJ into the Python script. Thanks!
And thank you for telling me about the GitHub actions, I had no idea that was a thing.
Kudos!!
